database:
  # the name of your JDBC driver
  driverClass: com.mysql.cj.jdbc.Driver

  # the username
  user: root

  # the password
  password: Password123#

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/BookStore

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect

  # the minimum number of connections to keep open
  minSize: 1

  # the maximum number of connections to keep open
  maxSize: 11